--- #YAML:1.0
name:                Net-Mosso-CloudFiles
version:             0.34
abstract:            Interface to Mosso CloudFiles service
license:             perl
author:              
    - Leon Brocard <acme@astray.com>
generated_by:        ExtUtils::MakeMaker version 6.44
distribution_type:   module
requires:     
    Digest::MD5:                   0
    Digest::MD5::File:             0
    LWP:                           0
    LWP::UserAgent::Determined:    0
    Moose:                         0
    MooseX::StrictConstructor:     0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
